/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'



export function Dav(props) {
	const { nodes, materials } = useGLTF("/gltf/TroquelMuebleMadera.gltf");
	return (
	  <group {...props} dispose={null} scale={.45} position={[0,.1,0]}>
		<pointLight
		  intensity={167804.547}
		  decay={2}
		  position={[1.242, 300.784, 20.412]}
		  rotation={[-1.839, 0.602, 1.932]}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom"].geometry}
		  material={materials["a1.001"]}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom_1"].geometry}
		  material={materials.a2}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom_2"].geometry}
		  material={materials.a3}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom002"].geometry}
		  material={materials["a1.001"]}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom002_1"].geometry}
		  material={materials.a2}
		/>
		<mesh
		  castShadow
		  receiveShadow
		  geometry={nodes["TQ_ARD_D13-geom002_2"].geometry}
		  material={materials.a3}
		/>
	  </group>
	);
  }
// useGLTF.preload('D:/_DIL/WEB/GALAAT/public/gltf/Troquel1G0102.gltf');

const Troquel1g0102 = ({}) => {
	return (

			<Canvas
				style={{  }}
				camera={{
					view: {
						enabled: true,
						fullWidth: 100,
						fullHeight: 100,
						offsetX: 0,
						offsetY: -30,
						width: 100,
						height: 100
					},
					focus: 10,
					fov: 80,
					zoom: 2.5
          ,
					position: [0, 1, 1.5]
				}} >
				<ambientLight intensity={2} />
				{/* <pointLight position={[10, 10, 2]} /> */}
				<Suspense fallback={null}>

					<Dav/>

				</Suspense>
				<OrbitControls autoRotate autoRotateSpeed={1} />
				<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
			</Canvas>
	)
}
export default Troquel1g0102
