/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'




export function Dav(props) {
	const { nodes, materials } = useGLTF("/gltf/TroquelMaleta.gltf");
	return (
	  <group {...props} dispose={null} scale={2.5} position={[0,.1,0]}>
		{/* <mesh
		  castShadow
		  receiveShadow
		  geometry={nodes.Plano.geometry}
		  material={nodes.Plano.material}
		/> */}
		<pointLight
		  intensity={90794.849}
		  decay={2}
		  position={[-0.248, 50.034, 50.966]}
		  rotation={[-1.839, 0.602, 1.932]}
		/>
		<group position={[0, 0.162, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom"].geometry}
			material={materials.TQ_ARD_front}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom_1"].geometry}
			material={materials.TQ_ARD_back}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom_2"].geometry}
			material={materials.TQ_ARD_edge}
		  />
		</group>
	  </group>
	);
  }

const Troquel1g0102 = ({}) => {
	return (

			<Canvas
				style={{  }}
				camera={{
					view: {
						enabled: true,
						fullWidth: 100,
						fullHeight: 100,
						offsetX: 0,
						offsetY: -30,
						width: 100,
						height: 100
					},
					focus: 10,
					fov: 80,
					zoom: 2.5
          ,
					position: [0, 1, 1.5]
				}} >
				<ambientLight intensity={2} />
				{/* <pointLight position={[10, 10, 2]} /> */}
				<Suspense fallback={null}>

					<Dav/>

				</Suspense>
				<OrbitControls autoRotate autoRotateSpeed={1} />
				<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
			</Canvas>
	)
}
export default Troquel1g0102
