/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'



export function Dav(props) {
	const { nodes, materials } = useGLTF("/gltf/TroquelMando.gltf");
	return (
	  <group {...props} dispose={null} scale={3} position={[0,.3,0]} >
		<pointLight
		  intensity={1351.413}
		  decay={2}
		  position={1.822, 3.724, -0.626}
		  rotation={[-1.839, 0.602, 1.932]}
		/>
		<group position={[-0.079, 0, 0.017]} rotation={[0, 0.117, 0]}>
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001"].geometry}
			material={materials["TQ_ARD_front.001"]}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001_1"].geometry}
			material={materials["back-dil"]}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001_2"].geometry}
			material={materials["TQ_ARD_edge.001"]}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001_3"].geometry}
			material={materials.TQ_ARD_front}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001_4"].geometry}
			material={materials.TQ_ARD_back}
		  />
		  <mesh
			castShadow
			receiveShadow
			geometry={nodes["TQ_ARD-geom001_5"].geometry}
			material={materials.TQ_ARD_edge}
		  />
		</group>
	  </group>
	);
  }

const Troquel1g0102 = ({}) => {
	return (

			<Canvas
				style={{  }}
				camera={{
					view: {
						enabled: true,
						fullWidth: 100,
						fullHeight: 100,
						offsetX: 0,
						offsetY: -30,
						width: 100,
						height: 100
					},
					focus: 10,
					fov: 80,
					zoom: 2.5
          ,
					position: [0, 1, 1.5]
				}} >
				<ambientLight intensity={2} />
				{/* <pointLight position={[10, 10, 2]} /> */}
				<Suspense fallback={null}>

					<Dav/>

				</Suspense>
				<OrbitControls autoRotate autoRotateSpeed={1} />
				<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
			</Canvas>
	)
}
export default Troquel1g0102
