/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'

export function Dav(props) {
  const { nodes, materials } = useGLTF("/gltf/Troquel1G0198.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.241, 0.250, -0.059]}
        rotation={[Math.PI, -0.087, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001"].geometry}
          material={materials["AAA_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001_1"].geometry}
          material={materials["AAA_ARD_back.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001_2"].geometry}
          material={materials["AAA_ARD_edge.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001_3"].geometry}
          material={materials.AAA_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001_4"].geometry}
          material={materials.AAA_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["AAA_ARD-geom001_5"].geometry}
          material={materials.AAA_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/Troquel1g0011.gltf");

const Troquel1g0011 = ({}) => {
	return (

			<Canvas
				style={{  }}
				camera={{
					view: {
						enabled: true,
						fullWidth: 100,
						fullHeight: 100,
						offsetX: 0,
						offsetY: -30,
						width: 100,
						height: 100
					},
					focus: 10,
					fov: 80,
					zoom: 2.5
          ,
					position: [0, 0.5, 1.5]
				}} >
				<ambientLight intensity={3} />
				{/* <pointLight position={[10, 10, 2]} /> */}
				<Suspense fallback={null}>

					<Dav/>

				</Suspense>
				<OrbitControls autoRotate autoRotateSpeed={1} />
				<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
			</Canvas>
	)
}
export default Troquel1g0011
