/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'

export  function Dav(props) {
  const { nodes, materials }  = useGLTF("/gltf/Troquel1G0102.gltf");
  return (
    <group {...props} dispose={null} position={[-0.0, .3, 0.0]} scale={1.2}>
      <group position={[-0.101, -0.11, 0.103]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom"].geometry}
          material={materials._1G0102_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_1"].geometry}
          material={materials._1G0102_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_2"].geometry}
          material={materials._1P0011_ARD_edge}
        />
      </group>
      <group
        position={[-0.173, -0.103, -0.006]}
        rotation={[Math.PI, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom"].geometry}
          material={materials["_1G0102_ARD_front.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_1"].geometry}
          material={materials["_1G0102_ARD_back.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_2"].geometry}
          material={materials._1P0011_ARD_D2_edge}
        />
      </group>
      <group
        position={[-0.101, -0.103, -0.006]}
        rotation={[Math.PI, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom"].geometry}
          material={materials["_1G0102_ARD_front.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_1"].geometry}
          material={materials["_1G0102_ARD_back.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_2"].geometry}
          material={materials._1P0011_ARD_D2_edge}
        />
      </group>
      <group
        position={[-0.029, -0.103, -0.006]}
        rotation={[Math.PI, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom"].geometry}
          material={materials["_1G0102_ARD_front.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_1"].geometry}
          material={materials["_1G0102_ARD_back.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD_D2-geom_2"].geometry}
          material={materials._1P0011_ARD_D2_edge}
        />
      </group>
      <group position={[-0.101, -0.11, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom"].geometry}
          material={materials._1G0102_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_1"].geometry}
          material={materials._1G0102_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_2"].geometry}
          material={materials._1P0011_ARD_edge}
        />
      </group>
      <group position={[-0.101, -0.11, -0.042]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom"].geometry}
          material={materials._1G0102_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_1"].geometry}
          material={materials._1G0102_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_2"].geometry}
          material={materials._1P0011_ARD_edge}
        />
      </group>
      <group position={[-0.101, -0.11, -0.114]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom"].geometry}
          material={materials._1G0102_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_1"].geometry}
          material={materials._1G0102_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1P0011_ARD-geom_2"].geometry}
          material={materials._1P0011_ARD_edge}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1G0102_ARD-geom"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1G0102_ARD-geom_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1G0102_ARD-geom_2"].geometry}
        material={materials._1G0102_ARD_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011---1_ARD-geom"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011---1_ARD-geom_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011---1_ARD-geom_2"].geometry}
        material={materials["_1P0011---1_ARD_edge"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom004"].geometry}
        material={materials._1G0102_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom004_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom004_2"].geometry}
        material={materials._1P0011_ARD_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom003"].geometry}
        material={materials["_1G0102_ARD_front.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom003_1"].geometry}
        material={materials["_1G0102_ARD_back.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom003_2"].geometry}
        material={materials._1P0011_ARD_D2_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom002"].geometry}
        material={materials["_1G0102_ARD_front.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom002_1"].geometry}
        material={materials["_1G0102_ARD_back.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom002_2"].geometry}
        material={materials._1P0011_ARD_D2_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom001"].geometry}
        material={materials["_1G0102_ARD_front.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom001_1"].geometry}
        material={materials["_1G0102_ARD_back.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD_D2-geom001_2"].geometry}
        material={materials._1P0011_ARD_D2_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom003"].geometry}
        material={materials._1G0102_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom003_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom003_2"].geometry}
        material={materials._1P0011_ARD_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom002"].geometry}
        material={materials._1G0102_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom002_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom002_2"].geometry}
        material={materials._1P0011_ARD_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom001"].geometry}
        material={materials._1G0102_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom001_1"].geometry}
        material={materials._1G0102_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1P0011_ARD-geom001_2"].geometry}
        material={materials._1P0011_ARD_edge}
      />
    </group>
  );
}


// useGLTF.preload('D:/_DIL/WEB/GALAAT/public/gltf/Troquel1G0102.gltf');

const Troquel1g0102 = ({}) => {
	return (

			<Canvas
				style={{  }}
				camera={{
					view: {
						enabled: true,
						fullWidth: 100,
						fullHeight: 100,
						offsetX: 0,
						offsetY: -30,
						width: 100,
						height: 100
					},
					focus: 10,
					fov: 80,
					zoom: 2.5
          ,
					position: [0, 0.5, 1.5]
				}} >
				<ambientLight intensity={2} />
				{/* <pointLight position={[10, 10, 2]} /> */}
				<Suspense fallback={null}>

					<Dav/>

				</Suspense>
				<OrbitControls autoRotate autoRotateSpeed={1} />
				<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
			</Canvas>
	)
}
export default Troquel1g0102
